# Generated by Django 2.1.5 on 2019-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('middle_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='pic_folder/')),
                ('phone_no', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(choices=[('ahmedabad', 'ahmedabad'), ('baroda', 'baroda'), ('palanpur', 'palanpur'), ('gandhinagar', 'gandhinagar'), ('unjha', 'unjha'), ('mehsana', 'mehsana')], max_length=20)),
            ],
        ),
    ]
