# Generated by Django 2.1.5 on 2019-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190620_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password1',
            field=models.CharField(default='12344', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password2',
            field=models.CharField(default='12344', max_length=50),
        ),
    ]
